# Autogenerated wrapper script for LASzip_jll for aarch64-apple-darwin
export liblaszip

JLLWrappers.@generate_wrapper_header("LASzip")
JLLWrappers.@declare_library_product(liblaszip, "@rpath/liblaszip.8.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        liblaszip,
        "lib/liblaszip.8.0.5.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
