# Autogenerated wrapper script for LASzip_jll for i686-w64-mingw32
export liblaszip

JLLWrappers.@generate_wrapper_header("LASzip")
JLLWrappers.@declare_library_product(liblaszip, "liblaszip3.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        liblaszip,
        "bin\\liblaszip3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
